name: Real DevOps Pipeline

on:
  push:
    branches: ["main"]

jobs:
  # 1. ЭТАП САМОПРОВЕРКИ (CI)
  validate-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Validate JSON syntax
        # Эта команда попытается прочитать JSON. Если там ошибка (нет запятой, скобки), она упадет с ошибкой
        run: |
          echo "Проверяем синтаксис config.json..."
          cat config.json | jq .
          echo "Проверка успешна! Конфиг валиден."

  # 2. ЭТАП ДЕПЛОЯ (CD)
  deploy-to-prod:
    runs-on: ubuntu-latest
    needs: validate-config # Этот этап начнется ТОЛЬКО если предыдущий успешен
    environment: 
      name: production # Мы указываем, что это окружение "production"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy to Production
        run: |
          echo "========================================="
          echo "✅ ДЕПЛОЙ НА ПРОД УСПЕШНО ВЫПОЛНЕН!"
          echo "Файл config.json версии $(jq -r .version config.json) развернут."
          echo "========================================="
